### ISSUE TITLE
mysql-connector dependency

### ISSUE THREAD

**Issue by tschoonj** [conda-forge/ispyb-feedstock#22]
@KarlLevik @Anthchirp @jacobfilik

https://github.com/DiamondLightSource/ispyb-api/blob/752a0d7152513fe0d879e8d09172d016a0860ee5/setup.py#L18

states that `mysql-connector` is a dependency and must be < 2.2.3

https://github.com/conda-forge/ispyb-feedstock/blob/bbe4054ffc03c75ee7a80f0854f8717960140dad/recipe/meta.yaml#L29

on the other hand lists `mysql-connector-python` as dependency without any version constraints.

The result is that installing `ispyb` yields:

```
mysql-connector-c         6.1.11            hd2bbab6_1003    conda-forge
mysql-connector-python    8.0.17           py37h7adf49d_0    conda-forge
```

which in turn breaks `zocalo.wrap`:

```
$ zocalo.wrap --wrap generic_process
Traceback (most recent call last):
  File "/dls_sw/apps/python/anaconda/4.6.14/64/envs/zocalo-stable/bin/zocalo.wrap", line 12, in <module>
    sys.exit(run())
  File "/dls_sw/apps/python/anaconda/4.6.14/64/envs/zocalo-stable/lib/python3.7/site-packages/zocalo/cli/wrap.py", line 129, in run
    instance = known_wrappers[options.wrapper]()()
  File "/dls_sw/apps/python/anaconda/4.6.14/64/envs/zocalo-stable/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2433, in load
    self.require(*args, **kwargs)
  File "/dls_sw/apps/python/anaconda/4.6.14/64/envs/zocalo-stable/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2456, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/dls_sw/apps/python/anaconda/4.6.14/64/envs/zocalo-stable/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'mysql-connector<2.2.3' distribution was not found and is required by ispyb
```

Any thoughts?

Note: I only got this far by pip installing `enum-compat` -> see https://github.com/DiamondLightSource/ispyb-api/pull/83

**Comment by Anthchirp** [comment]
The version restraint was introduced due to https://github.com/sanpingz/mysql-connector/issues/4
It looks like the mysql-connector package has now been deprecated entirely, so we should probably move to https://pypi.org/project/mysql-connector-python

**Comment by Anthchirp** [comment]
With #25 merged this should now be fixed.
